version: "3.9"
services:
  AuthorizationServiceDatabase:
    image: postgres:17.4-alpine3.21
    container_name: AuthorizationServiceDatabase
    env_file:
      - .env.AuthorizationServiceDatabase
    ports:
      - "5432:5432"

  AuthorizationService:
    image: authorization-service
    container_name: AuthorizationService
    build:
      context: /AuthorizationService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - AuthorizationServiceDatabase