spring.application.name=Authorization service
spring.profiles.active=dev

server.port=8080

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DATABASE_DRIVER}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=none

security.jwt.issuer=${SECURITY_JWT_ISSUER}
security.jwt.secret=${SECURITY_JWT_SECRET}