spring.application.name=Authorization service

server.port=8080

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=none

security.jwt.issuer=
security.jwt.secret=