version: "3.9"
name: wallet-control-microservices

services:
  DB_UserService:
    image: postgres:17.4-alpine3.21
    container_name: DB_UserService
    env_file:
      - .env.DB_UserService
    networks:
      - databases_network
    ports:
      - "5432:5432"

  UserService:
    image: user-service
    container_name: UserService
    build:
      context: ../UserService
      dockerfile: Dockerfile
    networks:
      - databases_network
      - microservices_network
    depends_on:
      - DB_UserService

  GatewayService:
    image: gateway-service
    container_name: GatewayService
    build:
      context: ../GatewayService
      dockerfile: Dockerfile
    networks:
      - gateway_network
      - microservices_network
    ports:
      - "8080:8080"

networks:
  databases_network:
  microservices_network:
  gateway_network: